language: node_js
dist: trusty
node_js:
  - v8
  - v9
before_script:
  - npm install coveralls codecov
script:
  - npm run check
  - npm run test
after_success:
  - 'cat ./coverage/lcov.info | coveralls'
  - 'cat ./coverage/lcov.info | codecov'
